### ISSUE TITLE
Decide on publicly exposed import structure of the app

### ISSUE THREAD

**Issue by crccheck** [CondeNast/launch-vehicle-fbm#21]
I assigned Jeff and I, but this is for everyone.

This is the final blocker to using this SDK in existing projects. Right now, we have to go into the source to import modules we're interested in:
```
const { Generic, Text } = require('launch-vehicle-fbm/src/objects');
```

1. What should those imports look like?
2. How do we implement them in a way that's [tree-shaking](http://www.2ality.com/2015/12/webpack-tree-shaking.html) friendly?

**Comment by crccheck** [comment]
> let's ignore the fact that Objects is a terrible name that shouldn't be used for a second

Agreed. My original intention was to be a dumping ground for any generic object we made, but it's clear now that we only have to deal with Messenger send objects

**Comment by tswicegood** [comment]
I think that's a possible route, @stripethree. Something like:

```javascript
const launch = require('launch-vehicle-fbm');
const messenger = new launch.Messenger();
const myText = new launch.responses.Text('things a bot would say!');
const myImage = new launch.response.Image('some-url-to-an-image');
```
