### ISSUE TITLE
Add ability to associate each `.send()` with a page

### ISSUE THREAD

**Issue by crccheck** [CondeNast/launch-vehicle-fbm#30]
Currently, the sdk assumes that it's only deployed to one page. But if we want one bot to work on multiple pages, we need a way to decide which page a bot is talking to.

I'm also working on a "Slack Ghost" app that would let you type from Slack back to Messenger, and you'd have to manually assign the page

**Comment by crccheck** [comment]
This may be part of a bigger issue about multitenancy

**Comment by stripethree** [comment]
To be explicit, is there more definition to _deploying a bot to more than one page_ than that they share a web hook URL?

**Comment by crccheck** [comment]
The current interface lets you pick which pages your app can listen to. Example:
![screen shot 2017-02-27 at 5 44 49 pm](https://cloud.githubusercontent.com/assets/189908/23385265/79c409c8-fd14-11e6-95f9-5a0bf9b1da55.png)

So it seems like Facebook is encouraging users to make multitenant bots

The url looks something like https://developers.facebook.com/apps/3456736120893612012345/messenger/

**Comment by crccheck** [comment]
I was thinking about this in the shower this morning, and I think copying from hubot and hapi would give us a nice api too.

for example, instead of:

    on('text', ({senderId, text, session}) => messenger.send(senderId, new Text('pong')))

something like:

    on('text', ({senderId, text, session}, res) => res.send(new Text('pong')))
