### ISSUE TITLE
Add support for Text quick replies

### ISSUE THREAD

**Issue by crccheck** [CondeNast/launch-vehicle-fbm#60]
There's an `ImageQuickReply` but not a `TextQuickReply`. Why? Because we only needed image quick replies. It was a quick hack. It may seem obvious to just make a `TextQuickReply`, but quick replies **are not** a response type, they're modifiers to text, image, and template (when did they support template?) responses.

This proposes the interface:
* `new Text('foo').quickReplies(...quickReplies)`
* `new Image('https://i.imgur.com/izwcQLS.jpg').quickReplies(...quickReplies)`

Notes:
* this keeps the number of response types down
* chaining might feel weird, but it's a very common pattern and allows you to keep things one line

Some alternate interfaces:
* `TextQuickReply` -- explosion of types that kinda do the same thing, hard to maintain
* `new Text('foo', quickReplies[])` -- conflicts with existing Text functionality and absence of keyword arguments makes this hard to use
* `new Text({text: 'foo', quickReplies})` -- might as well not even have helpers if we have to create so much structure
* `response = new Text('foo'); response.addQuickReply('this'); response.addQuickReply('that')` -- takes many LOC, too verbose. Incrementally adding quick replies is a pretty good idea though
* `respone = new Text('foo'); response.addQuickReplies(...quickReplies)` -- same as above but more extensible with ES6 destructuring

Future questions:
* What happens if you chain `.quickReplies` to itself?
* `.quickReply()` or `.quickReplies()`?
* need an `.addQuickReplies()` for incremental replies?

quick reply docs: https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies

**Comment by gautamarora** [comment]
Thanks for creating this issue @crccheck, i will definitely find use for this when I start building out a bot next week and can help test it out.

**Comment by crccheck** [comment]
this is released in version 1.8.0
