### ISSUE TITLE
Usage of Messenger Password

### ISSUE THREAD

**Issue by gautamarora** [CondeNast/launch-vehicle-fbm#64]
As I was developing a bot which I had previously developed using vanilla express, I was expecting that messenger password was not going to be needed. So i stubbed in test values in the config and environment. But as I was testing the application, I realized that there is something in launch vehicle that expects to have the right messenger password.

Can you clarify the cases in what scenarios the messenger password is required, as well as what is the right place to put it - env or config?

**Comment by gautamarora** [comment]
regarding the env vs config, that question is relevant to other values like FB app id, page id, page access token, validation token that are in both the env and config.

**Comment by stripethree** [comment]
I'm not sure what you mean by the Messenger _password_; are you referring to the _app secret_, _page access token_, or something different?

Re: env versus config, all the items you mentioned should be in the env. The [`config`] package pulls them from the env based on what's in `custom_environment_variables.json`.

[`config`]: https://github.com/lorenwest/node-config

**Comment by gautamarora** [comment]
@stripethree i meant the app secret.

> pulls them from the env based on what's in custom_environment_variables.json

still a bit confused, should it be in `.env` or `default.json` or `custom_environment_variables.json`?
right now i have the same values in .env and default.json

**Comment by stripethree** [comment]
Reviewing some old issues and realized this never got a confirmation: `.env` is the answer here. The `default.json` and `custom_environment_variables.json` would only need to be edited in the event that the application is adding a new environment variable or changing the name of an existing one.
