### ISSUE TITLE
Command typo in bot building blog post

### ISSUE THREAD

**Issue by gautamarora** [CondeNast/launch-vehicle-fbm#65]
In the [bot building blog post](https://engineering.condenast.io/story/bot-building-with-launch-vehicle-fbm), there is a trailing . at the end of the cp config command that causes all exported values to end with a period and then the webhook validation from FB to App fails due to mismatched tokens.

```export $(cat .env | xargs).```

**Comment by stripethree** [comment]
Ah yes, it runs into the period at the end of the sentence. I added quotes around the command to differentiate, so it looks like this now: "`export $(cat .env | xargs)`".
